'use server';

import { db } from "@/lib/firebase";
import { collection, addDoc, serverTimestamp, getDocs, query, orderBy } from "firebase/firestore";
import type { CoFounderInput, CoFounderOutput } from "@/ai/flows/chat";

/**
 * Saves a single AI co-founder analysis session to Firestore.
 * @param userId - The ID of the user who initiated the session.
 * @param input - The input data provided by the user.
 * @param output - The output data generated by the AI.
 * @returns The ID of the newly created document.
 */
export async function saveCopilotSession(
  userId: string,
  input: CoFounderInput,
  output: CoFounderOutput
): Promise<string> {
  if (!userId) {
    throw new Error("User ID is required to save a session.");
  }

  try {
    const sessionCollectionRef = collection(db, 'users', userId, 'copilotSessions');
    const docRef = await addDoc(sessionCollectionRef, {
      createdAt: serverTimestamp(),
      prompt: input,
      response: output,
    });
    return docRef.id;
  } catch (error) {
    console.error("Error saving copilot session to Firestore:", error);
    // Depending on requirements, you might want to re-throw or handle this error.
    // For now, we log it, and the AI flow will continue.
    throw error;
  }
}

export type CopilotSession = {
    id: string;
    createdAt: Date;
    prompt: CoFounderInput;
    response: CoFounderOutput;
}

/**
 * Retrieves all copilot sessions for a given user.
 * @param userId - The ID of the user.
 * @returns A promise that resolves to an array of copilot sessions.
 */
export async function getUserCopilotSessions(userId: string): Promise<CopilotSession[]> {
    if (!userId) {
        throw new Error("User ID is required to fetch sessions.");
    }
    
    try {
        const sessionsCollectionRef = collection(db, 'users', userId, 'copilotSessions');
        const q = query(sessionsCollectionRef, orderBy('createdAt', 'desc'));
        const querySnapshot = await getDocs(q);
        
        const sessions: CopilotSession[] = querySnapshot.docs.map(doc => {
            const data = doc.data();
            return {
                id: doc.id,
                // Firestore timestamps need to be converted to JS Date objects
                createdAt: data.createdAt?.toDate(), 
                prompt: data.prompt,
                response: data.response,
            } as CopilotSession;
        });
        
        return sessions;
    } catch (error) {
        console.error("Error fetching user copilot sessions:", error);
        throw error;
    }
}
