'use server';

import { db } from "@/lib/firebase";
import { collection, addDoc, serverTimestamp } from "firebase/firestore";
import type { CoFounderInput, CoFounderOutput } from "@/ai/flows/chat";

/**
 * Saves a single AI co-founder analysis session to Firestore.
 * @param userId - The ID of the user who initiated the session.
 * @param input - The input data provided by the user.
 * @param output - The output data generated by the AI.
 */
export async function saveCopilotSession(
  userId: string,
  input: CoFounderInput,
  output: CoFounderOutput
) {
  if (!userId) {
    throw new Error("User ID is required to save a session.");
  }

  try {
    const sessionCollectionRef = collection(db, 'users', userId, 'copilotSessions');
    await addDoc(sessionCollectionRef, {
      createdAt: serverTimestamp(),
      prompt: input,
      response: output,
    });
  } catch (error) {
    console.error("Error saving copilot session to Firestore:", error);
    // Depending on requirements, you might want to re-throw or handle this error.
    // For now, we log it, and the AI flow will continue.
  }
}
